### ISSUE TITLE
Unable to generate multiple VFS into same package

### ISSUE THREAD

**Issue by curio77** [shurcooL/vfsgen#80] opened 2020-04-22 09:25 UTC
It is impossible to generate multiple vfsgen instances into the same package because the generated files will conflict due to each of them defining a `vfsgen۰FS` type.  To avoid this, the user should be able to specify the type name as well, or it should include the designated instance name.

**Comment by dmitshur** [comment] 2020-04-22 11:51
Yes, there is a limit of one vfsgen-generated filesystem variable per package with the current design. There are some advantages and disadvantage to it. In many cases, using a union filesystem removes the need for generating more than 1 FS per package, but otherwise multiple packages need to be used. See https://github.com/shurcooL/vfsgen/issues/23#issuecomment-246617745 for more details.

I'll close this as duplicate of #23.

**Closed by dmitshur** 2020-04-22 11:51 UTC
