### ISSUE TITLE
Support generating multiple variables

### ISSUE THREAD

**Issue by mlen** [shurcooL/vfsgen#29] opened 2017-04-25 20:22 UTC
Please consider adding support for generating multiple variables, so that one can embed both static files to be served over http and templates while having them accessible via separate variables

**Comment by shurcooL** [comment] 2017-04-25 23:09
This is a duplicate of #23, I'll rename that issue to be more discoverable and redirect you there. Worth nothing is that there's an open PR #25 that implements a fix.

**Closed by shurcooL** 2017-04-25 23:09 UTC
Labels: duplicate
